FROM golang:1.24-bookworm AS go-builder
WORKDIR /app

COPY lb/go.mod ./
COPY lb/main.go .

RUN go mod tidy && go mod download
RUN CGO_ENABLED=0 GOOS=linux GOAMD64=v3 go build -ldflags="-s -w" -o rinha-lb .

FROM gcr.io/distroless/cc-debian12:latest
WORKDIR /app

COPY --from=go-builder /app/rinha-lb .
CMD ["./rinha-lb"]
